//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<decimal> TuitionFee { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public bool IsPaid { get; set; }
        public string ForMonth { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
